import React from 'react';
import { X, Shield, FileText } from 'lucide-react';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  subtitle?: string;
  content?: string;
  type: 'CASE_STUDY' | 'INTEL';
}

const ReportModal: React.FC<ReportModalProps> = ({ isOpen, onClose, title, subtitle, content, type }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-navy-900/95 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      ></div>

      {/* Modal Content */}
      <div className="relative bg-navy-900 w-full max-w-4xl h-[90vh] flex flex-col border border-bronze-500 shadow-[0_0_50px_rgba(212,175,55,0.1)] overflow-hidden animate-in fade-in zoom-in-95 duration-300">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-700 bg-navy-800 shrink-0">
          <div className="flex items-center gap-4">
            <div className={`p-3 rounded-full ${type === 'CASE_STUDY' ? 'bg-red-900/20 text-alert-red' : 'bg-bronze-900/20 text-bronze-500'}`}>
              {type === 'CASE_STUDY' ? <Shield className="w-6 h-6" /> : <FileText className="w-6 h-6" />}
            </div>
            <div>
              <div className="font-mono text-xs text-slate-500 uppercase tracking-widest mb-1">
                {type === 'CASE_STUDY' ? 'Classified Forensic Report' : 'Intelligence Briefing'}
              </div>
              <h2 className="font-serif text-xl md:text-2xl text-white font-bold leading-none">{title}</h2>
              {subtitle && <p className="font-sans text-sm text-slate-400 mt-1 italic">{subtitle}</p>}
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-slate-700 rounded-full transition-colors text-slate-400 hover:text-white"
          >
            <X className="w-8 h-8" />
          </button>
        </div>

        {/* Scrollable Body */}
        <div className="flex-grow overflow-y-auto p-6 md:p-10 custom-scrollbar bg-paper-100/5">
          {content ? (
            <div 
              className="prose prose-invert prose-lg max-w-none font-sans"
              dangerouslySetInnerHTML={{ __html: content }} 
            />
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-slate-500 opacity-50">
              <Lock className="w-16 h-16 mb-4" />
              <p className="font-mono uppercase">Data Encrypted / Access Denied</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-700 bg-navy-900 flex justify-between items-center shrink-0">
          <div className="font-mono text-[10px] text-slate-600 uppercase">
            Generated by BDSMETRO Engine v2.5
          </div>
          <button 
             onClick={onClose}
             className="bg-bronze-600 text-navy-900 font-mono font-bold px-6 py-2 hover:bg-bronze-500 transition-colors text-sm uppercase"
          >
            Đóng Hồ Sơ
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;